/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated.superadmin'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as StoreSlugIndexRouteImport } from './routes/store.$slug.index'
import { Route as StoreSlugShopRouteImport } from './routes/store.$slug.shop'
import { Route as StoreSlugCheckoutRouteImport } from './routes/store.$slug.checkout'
import { Route as StoreSlugCartRouteImport } from './routes/store.$slug.cart'
import { Route as StoreSlugProductIdRouteImport } from './routes/store.$slug.product.$id'
import { Route as AuthenticatedStoreSlugAdminRouteImport } from './routes/_authenticated.store.$slug.admin'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StoreSlugIndexRoute = StoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreSlugRoute,
} as any)
const StoreSlugShopRoute = StoreSlugShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreSlugRoute,
} as any)
const StoreSlugCheckoutRoute = StoreSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreSlugRoute,
} as any)
const StoreSlugCartRoute = StoreSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreSlugRoute,
} as any)
const StoreSlugProductIdRoute = StoreSlugProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreSlugRoute,
} as any)
const AuthenticatedStoreSlugAdminRoute =
  AuthenticatedStoreSlugAdminRouteImport.update({
    id: '/store/$slug/admin',
    path: '/store/$slug/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRouteWithChildren
  '/store/$slug/cart': typeof StoreSlugCartRoute
  '/store/$slug/checkout': typeof StoreSlugCheckoutRoute
  '/store/$slug/shop': typeof StoreSlugShopRoute
  '/store/$slug/': typeof StoreSlugIndexRoute
  '/store/$slug/admin': typeof AuthenticatedStoreSlugAdminRoute
  '/store/$slug/product/$id': typeof StoreSlugProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug/cart': typeof StoreSlugCartRoute
  '/store/$slug/checkout': typeof StoreSlugCheckoutRoute
  '/store/$slug/shop': typeof StoreSlugShopRoute
  '/store/$slug': typeof StoreSlugIndexRoute
  '/store/$slug/admin': typeof AuthenticatedStoreSlugAdminRoute
  '/store/$slug/product/$id': typeof StoreSlugProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRouteWithChildren
  '/store/$slug/cart': typeof StoreSlugCartRoute
  '/store/$slug/checkout': typeof StoreSlugCheckoutRoute
  '/store/$slug/shop': typeof StoreSlugShopRoute
  '/store/$slug/': typeof StoreSlugIndexRoute
  '/_authenticated/store/$slug/admin': typeof AuthenticatedStoreSlugAdminRoute
  '/store/$slug/product/$id': typeof StoreSlugProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin'
    | '/superadmin'
    | '/product/$id'
    | '/store/$slug'
    | '/store/$slug/cart'
    | '/store/$slug/checkout'
    | '/store/$slug/shop'
    | '/store/$slug/'
    | '/store/$slug/admin'
    | '/store/$slug/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin'
    | '/superadmin'
    | '/product/$id'
    | '/store/$slug/cart'
    | '/store/$slug/checkout'
    | '/store/$slug/shop'
    | '/store/$slug'
    | '/store/$slug/admin'
    | '/store/$slug/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/_authenticated/admin'
    | '/_authenticated/superadmin'
    | '/product/$id'
    | '/store/$slug'
    | '/store/$slug/cart'
    | '/store/$slug/checkout'
    | '/store/$slug/shop'
    | '/store/$slug/'
    | '/_authenticated/store/$slug/admin'
    | '/store/$slug/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  ProductIdRoute: typeof ProductIdRoute
  StoreSlugRoute: typeof StoreSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/store/$slug/': {
      id: '/store/$slug/'
      path: '/'
      fullPath: '/store/$slug/'
      preLoaderRoute: typeof StoreSlugIndexRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/store/$slug/shop': {
      id: '/store/$slug/shop'
      path: '/shop'
      fullPath: '/store/$slug/shop'
      preLoaderRoute: typeof StoreSlugShopRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/store/$slug/checkout': {
      id: '/store/$slug/checkout'
      path: '/checkout'
      fullPath: '/store/$slug/checkout'
      preLoaderRoute: typeof StoreSlugCheckoutRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/store/$slug/cart': {
      id: '/store/$slug/cart'
      path: '/cart'
      fullPath: '/store/$slug/cart'
      preLoaderRoute: typeof StoreSlugCartRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/store/$slug/product/$id': {
      id: '/store/$slug/product/$id'
      path: '/product/$id'
      fullPath: '/store/$slug/product/$id'
      preLoaderRoute: typeof StoreSlugProductIdRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/_authenticated/store/$slug/admin': {
      id: '/_authenticated/store/$slug/admin'
      path: '/store/$slug/admin'
      fullPath: '/store/$slug/admin'
      preLoaderRoute: typeof AuthenticatedStoreSlugAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedStoreSlugAdminRoute: typeof AuthenticatedStoreSlugAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedStoreSlugAdminRoute: AuthenticatedStoreSlugAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface StoreSlugRouteChildren {
  StoreSlugCartRoute: typeof StoreSlugCartRoute
  StoreSlugCheckoutRoute: typeof StoreSlugCheckoutRoute
  StoreSlugShopRoute: typeof StoreSlugShopRoute
  StoreSlugIndexRoute: typeof StoreSlugIndexRoute
  StoreSlugProductIdRoute: typeof StoreSlugProductIdRoute
}

const StoreSlugRouteChildren: StoreSlugRouteChildren = {
  StoreSlugCartRoute: StoreSlugCartRoute,
  StoreSlugCheckoutRoute: StoreSlugCheckoutRoute,
  StoreSlugShopRoute: StoreSlugShopRoute,
  StoreSlugIndexRoute: StoreSlugIndexRoute,
  StoreSlugProductIdRoute: StoreSlugProductIdRoute,
}

const StoreSlugRouteWithChildren = StoreSlugRoute._addFileChildren(
  StoreSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  ProductIdRoute: ProductIdRoute,
  StoreSlugRoute: StoreSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
